### ISSUE TITLE
地面のcoordIndexの計算

### ISSUE THREAD

**Issue by light-vr** [Inat-qingbao/gaei_cpp#5]
入力された点の集合を三角形の平面に分割するプログラムが必要

**Comment by ouchiminh** [comment]
ドロネーの三角形分割を実装してcoordIndexを計算する

**Comment by ouchiminh** [comment]
`std::vector<gaei::vertex<gaei::vec3f, gaei::color>>`を入力し`std::vector<std::tuple<size_t, size_t, size_t>>`を返す。
戻り値の`std::tuple<size_t, size_t, size_t>`はそれぞれ三角形を構成する各点のインデックスとなる。
例えば、引数の`std::vector<...>`の0番目、1番目、2番目の頂点が三角形を構成するならば戻り値の要素の一つは`0`, `1`, `2`を順不同でひとつずつ含む`std::tuple<size_t, size_t, size_t>`のインスタンスである。

**Comment by light-vr** [comment]
関数のsignatureは以下のとおり
```cpp
std::vector<std::tuple<size_t, size_t, size_t>> delaunay_triangulation(const std::vector<gaei::vertex<>>&)
```
